### ISSUE TITLE
关于Nginx的配置的咨询？

### ISSUE THREAD

**Issue by Linpean** [Jerrywang959/notion-reverse-proxy#1]
@Jerrywang959 
作为1个使用Notion创建游戏Wiki的站长 ： www.gjqtwiki.com
最近也在折腾Notion的反向代理，但奈何对Nginx一窍不通。勉强在宝塔里面折腾完成了。
但是最近访问速度直线下降，想咨询下如果优化访问速度。
方便的话，可否加个QQ：1107099465 交流下

**Comment by noyyyy** [comment]
如果是静态wiki，而且要用自己的域名，建议静态改写。最简单的就是 https://github.com/transitive-bullshit/nextjs-notion-starter-kit    github上还有其他很多项目
如果懒得配置肯花钱可以用 https://super.so   我感觉这个目前做的最好

**Comment by noyyyy** [comment]
看起来你想搞成可以编辑的。但是又允许公共编辑，有想有自己的域名  是无法实现的

**Comment by noyyyy** [comment]
你这个数据库还是蛮多的  https://github.com/transitive-bullshit/nextjs-notion-starter-kit 这个对数据库渲染不太好   还是建议花钱吧  super.so 还有其他很多类似的网站

**Comment by Linpean** [comment]
> 你这个数据库还是蛮多的 https://github.com/transitive-bullshit/nextjs-notion-starter-kit 这个对数据库渲染不太好 还是建议花钱吧 super.so 还有其他很多类似的网站

我很早就看了super.so机房速度不行，甚至在17ce.com一半的国内节点会直接GG了，现在用的机房是香港59元/月。

**Comment by noyyyy** [comment]
> > 你这个数据库还是蛮多的 https://github.com/transitive-bullshit/nextjs-notion-starter-kit 这个对数据库渲染不太好 还是建议花钱吧 super.so 还有其他很多类似的网站
> 
> 我很早就看了super.so机房速度不行，甚至在17ce.com一半的国内节点会直接GG了，现在用的机房是香港59元/月。

super.so现在跟原来不一样了，很大不同，原来只是反代，现在有重写
