### ISSUE TITLE
你的博客文章无法打开

### ISSUE THREAD

**Issue by Mvbbb** [Jerrywang959/notion-reverse-proxy#2]
时间 2021年2月12日21:38:42
![image](https://user-images.githubusercontent.com/56795364/107775006-ba104c00-6d7a-11eb-9271-83a4e3174627.png)
![image](https://user-images.githubusercontent.com/56795364/107775025-bed50000-6d7a-11eb-95e5-9e40d3a4bef6.png)

**Comment by Mvbbb** [comment]
Notion dns故障

**Comment by noyyyy** [comment]
要不 ctrl+shift+R 刷新一下？
抱歉我才看到  昨天Notion都挂了。。。 这是系统性风险，我无能为力  <https://status.notion.so/>

![图片](https://user-images.githubusercontent.com/59097122/107851946-75eb7d00-6e48-11eb-8172-1f4fb792eae7.png)
