### ISSUE TITLE
你好，咨询一下你的个人网站

### ISSUE THREAD

**Issue by Hoodrh** [Jerrywang959/notion-reverse-proxy#3]
你好，发现你的个人网站很好看，是否可以将网站代码开源呢，谢谢

**Comment by noyyyy** [comment]
> 你好，发现你的个人网站很好看，是否可以将网站代码开源呢，谢谢

https://github.com/transitive-bullshit/nextjs-notion-starter-kit

**Comment by Hoodrh** [comment]
谢谢
