### ISSUE TITLE
安卓的改DNS方式已经失效一个月

### ISSUE THREAD

**Issue by MCR-LTS** [Jerrywang959/notion-reverse-proxy#4]
npstatus.jerryw.cn 上显示，DOH从2.15 8:00开始终止服务至今。无论是在安卓上改dns还是在iPhone上下载描述文件，都会因dns失效而导致整机网络功能瘫痪。改hosts文件目前没有问题。
<img width="599" alt="image" src="https://github.com/noyyyy/notion-reverse-proxy/assets/90949899/1e611aae-ebe2-4bc6-9b04-0b3baa795769">
如果作者已经在其他地方宣告停止维护，抱歉我没有看到。
如果本情况属于作者所列的“免责声明”中的一款，抱歉我的语文理解能力实在太差。
本人社恐，未加入任何一个谈论群组。如已有人反映过类似问题请无视。
如果本需求过于小众，作者可以忽略。感谢。

**Comment by noyyyy** [comment]
抱歉，我确实不是一直盯着监控在看的。我没有 ios ，所以不太能实时检测 ios 的情况。但是我的安卓手机一直在用私人DNS是没有问题的，安卓系统默认用的是 DOT。之前DNS主要由于证书过期掉了，我也很快就修复了。没有收到你说的一直无法使用的反馈。
![img_v3_0293_677d0673-ddda-459b-bf09-d957fbdebdhu](https://github.com/noyyyy/notion-reverse-proxy/assets/59097122/f8e286ce-0dd9-423f-8ec7-90b77db328dc)

**Comment by noyyyy** [comment]
我确认了一下，DOH显示一直挂了主要是因为监控的服务商 better uptime 把那一条暂停了，所以恢复了之后也没有一直响应....
感谢你的反馈，更欢迎你加入讨论群组，那样可以得到更及时的响应

**Comment by MCR-LTS** [comment]
现在正常了。感谢作者！
